:sparkles: (design system) : Add button-copy-paste
webians/webians-website-2021 pull request #57
Opened 2022-01-18 16:28 UTC by JenniferMrm

2022-01-19 09:54 UTC, HubM requested changes

2022-01-19 09:54 UTC, HubM commented on ui/components/globals/buttons/button-copy-paste/index.vue
> +      default: null
Si ce champ est pas requis du coup par défault le slot aura comme valeur `null`

2022-01-19 09:54 UTC, HubM commented on ui/components/globals/buttons/button-copy-paste/index.vue
> +      default: null
Et pourquoi mettre une value si il y a un slot ?

2022-01-19 10:08 UTC, antoinechassagne commented on ui/components/globals/buttons/button-copy-paste/index.vue
> +    <div>
à quoi sert cette div là ?

2022-01-19 10:08 UTC, antoinechassagne commented on ui/components/globals/buttons/button-copy-paste/index.vue
> +      validorat(value) {
`validorat` 🤔  😂

2022-01-19 15:23 UTC, antoinechassagne commented on ui/components/globals/buttons/button-copy-paste/index.vue
> +      validator: value => {
Essayons d'utiliser la même syntaxe que les validator plus bas

2022-01-19 15:23 UTC, antoinechassagne commented on ui/components/globals/buttons/button-copy-paste/index.vue
> +      </button-tertiary>
```html
<button-tertiary :tag="tag" :size="size" :textColor="textColor">
    <slot name="icon">
    </slot>
   {{ value }}
</button-tertiary>
```

2022-01-20 09:30 UTC, vivianeglz requested changes

2022-01-20 09:30 UTC, vivianeglz commented on ui/components/globals/buttons/button-copy-paste/button-copy-paste.test.js
> +  });
Avec le factory utilisé de cette manière tu n'as pas besoin du beforeEach, afterEach. Je te laisse regarder les exemples déjà existant

2022-01-20 09:30 UTC, vivianeglz commented on ui/components/globals/buttons/button-copy-paste/index.vue
> +      }
Attention ici `this.color` ne peut être que `dark`, `light` ou `stroked` (= comme le ButtonIcon )

2022-01-20 09:30 UTC, vivianeglz commented on ui/css/globals/_buttons.scss
> +
Il n'y a pas de `dark-colored` sur le button-icon

2022-01-20 09:30 UTC, vivianeglz commented on ui/css/globals/_buttons.scss
> +
same

2022-01-20 10:06 UTC, vivianeglz requested changes

2022-01-20 10:06 UTC, vivianeglz commented on ui/css/globals/_buttons.scss
> +  }
Normalement tu n'as pas besoin de tout ça, tu peux te débrouiller avec les props que tu passes aux composants du button-copy-past

2022-01-20 10:21 UTC, vivianeglz requested changes

2022-01-20 10:21 UTC, vivianeglz commented on ui/css/globals/_buttons.scss
> +    }
Ca tu peux l'enlever c'est quand on utilise l'icon dans le template que l'on passe directement la props de la couleur, ça ne sert à rien de surcharger avec du style

2022-01-20 10:31 UTC, vivianeglz approved these changes
👍

2022-01-20 10:31 UTC, merged